import json
import sys
from pathlib import Path

from docking.config_schema import RootConfig
from docking.workflows.charge_preparation import ChargeLigandWorkflow
from docking.workflows.dock6_preparation import Dock6Preparation
from docking.wrappers.vina_tools import PrepareLigandWrapper, VinaWrapper


def run_task(task_path: Path) -> None:
    """Run one ligand docking task generated by ParallelLigandDockingWorkflow."""
    with open(task_path) as handle:
        task = json.load(handle)

    cfg = RootConfig.model_validate(task["cfg"])
    working_dir = Path(task["working_dir"])
    ligand = task["ligand"]

    charged_ligand = ChargeLigandWorkflow(
        cfg,
        working_dir,
        output_type="mol2",
        ligand=ligand["smiles"],
        ligand_name=ligand["name"],
    ).run()

    if task["engine"] == "vina":
        prepared_ligand = PrepareLigandWrapper(
            binary_path=cfg.libs.prepare_ligand,
            working_dir=working_dir,
            input_file=charged_ligand,
        ).run()
        output_file, log_file = VinaWrapper(
            binary_path=cfg.libs.vina,
            working_dir=working_dir,
            receptor=task["prepared_receptor"],
            ligand=prepared_ligand,
            configs=task["vina_config"],
        ).run()
    elif task["engine"] == "dock6":
        output_file, log_file = Dock6Preparation(
            cfg=cfg,
            working_dir=working_dir,
            charged_receptor=task["charged_receptor"],
            charged_ligand=charged_ligand,
            flex_name=f"flex_{ligand['name']}.in",
        ).run()
    else:
        raise ValueError(f"Unknown docking engine: {task['engine']}")

    result = {
        "ligand": ligand["name"],
        "charged_ligand": charged_ligand,
        "output_file": str(output_file),
        "log_file": str(log_file),
    }
    result_path = task_path.with_suffix(".result.json")
    with open(result_path, "w") as handle:
        json.dump(result, handle, indent=2)


def main() -> int:
    if len(sys.argv) != 2:
        raise SystemExit("Usage: python -m docking.workflows.parallel_ligand_task TASK_JSON")
    run_task(Path(sys.argv[1]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
