libs:
  chimerax: "/usr/local/chimerax/bin/ChimeraX"
  obabel: "obabel"
  vina: "vina"
  dock6: "/usr/local/dock6/bin/dock6"
  prepare_receptor: "pythonsh /home/kbui/Downloads/mgltools_x86_64Linux2_1.5.7p1/mgltools_x86_64Linux2_1.5.7/MGLToolsPckgs/AutoDockTools/Utilities24/prepare_receptor4.py"
  prepare_ligand: "pythonsh /home/kbui/Downloads/mgltools_x86_64Linux2_1.5.7p1/mgltools_x86_64Linux2_1.5.7/MGLToolsPckgs/AutoDockTools/Utilities24/prepare_ligand4.py"
# FIX LATER

common:
  receptor: "/home/kbui/SARS_COV_2/data/8hqg.pdb"
  lig_option: "smiles" # "sdf" or "mol2" or "smiles"
  ligand: "CC(=O)OC1=CC=CC=C1C(=O)O" # path or string depending on lig_option
  lig_name: "aspirin"
  output_dir: "outputs/"
  pocket_name: "catalytic_site"

vina:
  exhaustiveness: 32
  num_modes: 8
  cpu: 1
  padding: 5.0
  pocket_option: "res" # "res" or "lig"
  reference: "data/ref_ligand.mol2" # used if pocket_option is "lig"
  residue_selection: "resi 41,165" # used if pocket_option is "res", should be a valid PyMOL selection string

dock6:
  max_orientations: 5000
  padding: 5.0
  residue_selection: [41,165] # receptor residues only